
   pipeline {
       agent any

       tools {
           maven 'Maven 3.9'
           jdk 'JDK 21'
       }

       environment {
           SERVICE_NAME = 'auth_service'
           SONAR_TOKEN  = credentials('sonar_recolte')
       }

       stages {

           stage('Checkout') {
               steps {
                   checkout scm
                   echo "Branch: ${env.BRANCH_NAME}"
               }
           }

           stage('Build') {
               steps {
                   sh 'mvn clean compile -q -f auth_service/pom.xml'
               }
           }

           stage('Tests') {
               steps {
                   sh 'mvn test -DskipTests -f auth_service/pom.xml'
               }
               /*post {
                    always {
                       junit 'auth_service/target/surefire-reports *//*.xml'
                   }
               }*/
           }

           stage('SonarQube') {
               steps {
                   withSonarQubeEnv('SonarQube') {
                       sh "mvn sonar:sonar -f auth_service/pom.xml -Dsonar.token=${SONAR_TOKEN}"
                   }
               }
           }

           stage('Package') {
               steps {
                   sh 'mvn package -DskipTests -q -f auth_service/pom.xml'
               }
           }
       }

       post {
           success {
               echo "✅ auth-service build réussi !"
           }
           failure {
               echo "❌ auth-service build échoué !"
           }
       }
   }