spring.application.name=api_gateway
server.port=8080

jwt.secret=agrisuivi_jwt_secret_key_256_bits_minimum_securite_2025

# EUREKA
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# ROUTES API
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:3001
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:3002
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/users/**

# ROUTES SWAGGER
spring.cloud.gateway.server.webflux.routes[2].id=auth-service-docs
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:3001
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/auth-service/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/auth-service/v3/api-docs(?<segment>/?.*), /v3/api-docs$\{segment}

spring.cloud.gateway.server.webflux.routes[3].id=users-service-docs
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:3002
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/users-service/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=RewritePath=/users-service/v3/api-docs(?<segment>/?.*), /v3/api-docs$\{segment}

# ACTUATOR
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# SWAGGER
springdoc.swagger-ui.urls[0].name=auth-service
springdoc.swagger-ui.urls[0].url=/auth-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=users-service
springdoc.swagger-ui.urls[1].url=/users-service/v3/api-docs