spring.application.name=geo_service'

server.port=3003

# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5435/agrisuivi_geo
spring.datasource.username=geo_user
spring.datasource.password=geo1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=agrisuivi_jwt_secret_key_256_bits_minimum_securite_2025

# EUREKA
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# ACTUATOR
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
logging.level.org.springframework.security=DEBUG
spring.security.user.name=disabled
spring.security.user.password=disabled
#appele de users service
users.service.base-url=http://localhost:3002