spring.application.name=auth_service
server.port=3001

# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5433/agrisuivi_auth
spring.datasource.username=auth_user
spring.datasource.password=auth1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis1234

#EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# tocken JWT
jwt.secret=agrisuivi_jwt_secret_key_256_bits_minimum_securite_2025
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# ACTUATOR (health check)
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
eureka.client.enabled=false
#l 'url du service user-service
users.service.base-url=http://localhost:3002
springdoc.swagger-ui.cors-enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html